stages:
  - security_scan

security_scan:
  stage: security_scan
  image: mcr.microsoft.com/powershell:latest
  script:
    - pwsh security_scan.ps1
  before_script:
    - echo "Running security scan with Fortify..."
  only:
    - main
